import{a as v,S as b,i as n}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const S="https://pixabay.com/api/",w="47378473-ac089f81fe0a13d2309255fc1";async function f(s,r=1,o=15){var e;const i={key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:o};try{const t=await v.get(S,{params:i});return console.log("Response data:",t.data),t.data}catch(t){throw new Error((e=t.response)==null?void 0:e.statusText)}}const P=new b(".gallery-list a");function h(s){const r=s.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:l,comments:y,downloads:L})=>`<li class="list-item">
  <a href="${i}" alt="${e}">
    <img src="${o}" alt="${e}" class="img-item">
  </a>
  <div class="list-container">
    <p class="item"><span class="item-text">Likes:</span> <span>${t}</span></p>
    <p class="item"><span class="item-text">Views:</span> <span>${l}</span></p>
    <p class="item"><span class="item-text">Comments:</span> <span>${y}</span></p>
    <p class="item"><span class="item-text">Downloads:</span> <span>${L}</span></p>
  </div>
</li>`).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function E(){const{height:s}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}function d(s){g.classList.toggle("hidden",!s)}const R=document.querySelector(".form-js"),m=document.querySelector(".list-js"),p=document.querySelector(".loader"),g=document.querySelector(".js-load-more");let u="",a=1;const c=15;R.addEventListener("submit",x);g.addEventListener("click",$);async function x(s){s.preventDefault();const{picture:r}=s.currentTarget.elements;if(r.value.trim()==="")return n.error({position:"topRight",message:"Fill out the form",backgroundColor:"#EF4040"});u=r.value.trim(),a=1,m.innerHTML="",d(!1),p.classList.remove("hidden");try{const o=await f(u,a,c);if(o.hits.length===0)return n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040"});h(o.hits),d(o.totalHits>a*c),a*c>=o.totalHits&&(d(!1),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(o){n.error({position:"topRight",message:o.message})}finally{p.classList.add("hidden")}}async function $(){a+=1,p.classList.remove("hidden");try{const s=await f(u,a,c);h(s.hits),d(s.totalHits>a*c),E(),a*c>=s.totalHits&&n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(s){n.error({position:"topRight",message:s.message})}finally{p.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
