import{S as d,i as a}from"./assets/vendor-5ObWk2rO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="https://pixabay.com/api",h="47378473-ac089f81fe0a13d2309255fc1";function g(o){const s=new URLSearchParams({key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${f}/?${s}`).then(r=>{if(!r.ok)throw new Error(r.statusText);return r.json()})}const y=new d(".list-item a");function L(o){const s=o.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:i,comments:m,downloads:u})=>`<li class="list-item" >
  <a href="${n}" alt="${e}" />
    <img src="${r}" alt="${e}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${t}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${i}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${m}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${u}</span></p>
  </div></a>
</li>`).join("");p.insertAdjacentHTML("beforeend",s),S.classList.replace("load-more-hidden","load-more"),y.refresh()}const l=document.querySelector(".form-js"),p=document.querySelector(".list-js"),c=document.querySelector(".loader"),S=document.querySelector(".js-load-more");l.addEventListener("submit",$);async function $(o){o.preventDefault();const{picture:s}=o.currentTarget.elements;if(s.value.trim()==="")return a.error({position:"topRight",message:"Fill out the form",backgroundColor:"#EF4040"});p.innerHTML="",c.classList.remove("hidden"),g(s.value.trim()).then(r=>{if(r.hits.length===0)return a.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040"});L(r.hits),l.reset()}).catch(r=>a.error({position:"topRight",message:r.message})).finally(()=>c.classList.add("hidden"))}
//# sourceMappingURL=index.js.map
