import{a as v,S as b,i as n}from"./assets/vendor-BDaiwwc1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="https://pixabay.com/api",w="47378473-ac089f81fe0a13d2309255fc1";async function h(t,s=1,a=15){const o={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:a};try{return(await v.get(S,{params:o})).data}catch{throw new Error(response.statusText)}}const P=new b(".gallery-list a");function f(t){const s=t.map(({webformatURL:a,largeImageURL:o,tags:e,likes:r,views:c,comments:y,downloads:L})=>`<li class="list-item">
  <a href="${o}" alt="${e}">
    <img src="${a}" alt="${e}" class="img-item">
  </a>
  <div class="list-container">
    <p class="item"><span class="item-text">Likes:</span> <span>${r}</span></p>
    <p class="item"><span class="item-text">Views:</span> <span>${c}</span></p>
    <p class="item"><span class="item-text">Comments:</span> <span>${y}</span></p>
    <p class="item"><span class="item-text">Downloads:</span> <span>${L}</span></p>
  </div>
</li>`).join("");m.insertAdjacentHTML("beforeend",s),P.refresh()}function E(){const{height:t}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function d(t){g.classList.toggle("hidden",!t)}const x=document.querySelector(".form-js"),m=document.querySelector(".list-js"),p=document.querySelector(".loader"),g=document.querySelector(".js-load-more");let u="",i=1;const l=15;x.addEventListener("submit",R);g.addEventListener("click",$);async function R(t){t.preventDefault();const{picture:s}=t.currentTarget.elements;if(s.value.trim()==="")return n.error({position:"topRight",message:"Fill out the form",backgroundColor:"#EF4040"});u=s.value.trim(),i=1,m.innerHTML="",d(!1),p.classList.remove("hidden");try{const o=(await h(u,i,l)).data;if(o.hits.length===0)return n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040"});f(o.hits),d(o.totalHits>l),n.success({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(a){n.error({position:"topRight",message:a.message})}finally{p.classList.add("hidden")}}async function $(){i+=1,p.classList.remove("hidden");try{const s=(await h(u,i,l)).data;f(s.hits),d(s.totalHits>i*l),E(),i*l>=s.totalHits&&n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(t){n.error({position:"topRight",message:t.message})}finally{p.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
